### REIGISTRATION
POST  http://localhost:80/registration
Content-Type: application/json

{
   "email": "kaino@bk.ru",
   "password": "134679",
   "name": "Шакир",
   "last_name": "Шакиров"
}

### LOGIN
POST  http://localhost:80/login
Content-Type: application/json

{
   "email": "admin@chatpnz.ru",
   "password": "134679"
}

### STANDINGS
GET  http://localhost:80/standings
Content-Type: application/json

### CHECK
GET   http://localhost:80/check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNoYXRwbnoucnUiLCJuYW1lIjoi0JDRgNGC0LXQvCIsImxhc3RfbmFtZSI6ItCo0LDQutC40YDQvtCyIiwicm9sZSI6InBsYXllciIsImlhdCI6MTY2MTk3NzE1OSwiZXhwIjoxNjY0NTY5MTU5fQ.qraDePjgKZD6VDoXTjzcm2iF7edDysgRUui-d-saSkc

### ALL BET
GET  http://localhost:80/all-bets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIm5hbWUiOiLQpNCw0LrRg9C7IiwibGFzdF9uYW1lIjoi0KTQsNC60YPQu9C-0LIiLCJyb2xlIjoicGxheWVyIiwiYmV0cyI6WzIyNTIzNTUsMjI1MjM1NV0sInBvaW50cyI6MCwiaWF0IjoxNjYyODkwOTk1LCJleHAiOjE2NjU0ODI5OTV9.ZjkSGJoLnIWsiFi9tWVTzOrFXbxcezbHOth7Kgb8C_A

{
   "email": "admin@chatpnz.ru",
   "password": "134679"
}

### GET PAST BETS
GET  http://localhost:80/past?limit=8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIm5hbWUiOiLQpNCw0LrRg9C7IiwibGFzdF9uYW1lIjoi0KTQsNC60YPQu9C-0LIiLCJyb2xlIjoicGxheWVyIiwiYmV0cyI6WzIyNTIzNTUsMjI1MjM1NV0sInBvaW50cyI6MCwiaWF0IjoxNjYyODkwOTk1LCJleHAiOjE2NjU0ODI5OTV9.ZjkSGJoLnIWsiFi9tWVTzOrFXbxcezbHOth7Kgb8C_A


### ALL PLAYERS
GET  http://localhost:80/all-players


### SERVER - players
GET  https://rpl-app-production.up.railway.app/all-players


### SERVER - login
POST https://rpl-app-production.up.railway.app/login
Content-Type: application/json

{
   "email": "admin@chatpnz.ru",
   "password": "134679"
}



### SERVER - my bets
GET   http://localhost:80/my-bets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNoYXRwbnoucnUiLCJuYW1lIjoi0JDRgNGC0LXQvCIsImxhc3RfbmFtZSI6ItCo0LDQutC40YDQvtCyIiwicm9sZSI6InN1cGVyLWFkbWluIiwiYmV0cyI6WzEzOTEwNzksMTM5MTA4MywxMzkxMDc4LDEzOTEwODQsMTM5MTA4MiwxMzkxMDc3XSwicG9pbnRzIjowLCJpYXQiOjE2NjI5MDI3NzcsImV4cCI6MTY2NTQ5NDc3N30.yl7hrDtVHGJIzFg6H9Y9t6TlvgOLufORu5ANAm7Eh0U

### SERVER - new bet
POST   http://localhost:80/new-bet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIm5hbWUiOiLQpNCw0LrRg9C7IiwibGFzdF9uYW1lIjoi0KTQsNC60YPQu9C-0LIiLCJyb2xlIjoicGxheWVyIiwiaWF0IjoxNjYyODA0Njg0LCJleHAiOjE2NjUzOTY2ODR9.flGU4z-mz7Gf2OjMPtji2JIROylq1GNsudGO-yLZMYE 

[
   {
      "event_id": 2252355,
      "home_score": 1,
      "away_score": 0,
      "status": false,
      "winner_code": 0,
      "bet_code": 2
   }
]


### SERVER - delete my bets
GET  http://localhost:80/delete-my-bets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNoYXRwbnoucnUiLCJuYW1lIjoi0JDRgNGC0LXQvCIsImxhc3RfbmFtZSI6ItCo0LDQutC40YDQvtCyIiwicm9sZSI6InN1cGVyLWFkbWluIiwiYmV0cyI6WzEzOTEwNzcsMTM5MTA3OSwxMzkxMDgzLDEzOTEwNzgsMTM5MTA4NCwxMzkxMDgyLDEzOTEwODEsMTM5MTA4MF0sInBvaW50cyI6MCwiaWF0IjoxNjYyOTc5NTcxLCJleHAiOjE2NjU1NzE1NzF9.d3lpP3ZPPCZ4ZPj9KEdfZWg0ld150i-9uo-oEuftHQI


### PLACEHOLDERs
GET  https://jsonplaceholder.typicode.com/posts


### SOKOLOVA
POST  http://pmsokolova.ru/post_check.php
Content-Type: application/json

[
   {
      "event_id": 2252355,
      "home_score": 1,
      "away_score": 0,
      "status": false,
      "winner_code": 0,
      "bet_code": 2
   }
]